services:
  app:
    image: isthistechsupport/tootbot:latest
    environment:
      - TOOTBOT_GENERAL_SUBREDDIT_TO_MONITOR
      - TOOTBOT_GENERAL_DELAY_BETWEEN_POSTS
      - TOOTBOT_GENERAL_POST_LIMIT
      - TOOTBOT_GENERAL_NSFW_POSTS_ALLOWED
      - TOOTBOT_GENERAL_SPOILERS_ALLOWED
      - TOOTBOT_GENERAL_SELF_POSTS_ALLOWED
      - TOOTBOT_GENERAL_HASHTAGS
      - TOOTBOT_MEDIA_MEDIA_FOLDER
      - TOOTBOT_MEDIA_MEDIA_POSTS_ONLY
      - TOOTBOT_REDDIT_AGENT
      - TOOTBOT_REDDIT_CLIENT_SECRET
      - TOOTBOT_IMGUR_CLIENT
      - TOOTBOT_IMGUR_CLIENT_SECRET
      - TOOTBOT_TWITTER_ACCESS_TOKEN
      - TOOTBOT_TWITTER_ACCESS_TOKEN_SECRET
      - TOOTBOT_TWITTER_CONSUMER_KEY
      - TOOTBOT_TWITTER_CONSUMER_SECRET
      - TOOTBOT_REDIS_HOST
      - TOOTBOT_REDIS_PORT
      - TOOTBOT_REDIS_PASSWORD
      - TOOTBOT_LOG_DESTINATION
      - TOOTBOT_LOG_PORT
    depends_on:
      - redisdb

  redisdb:
    image: redis:7-alpine
    restart: always
    ports:
      - '${TOOTBOT_REDIS_PORT}:${TOOTBOT_REDIS_PORT}'
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${TOOTBOT_REDIS_PASSWORD} --port ${TOOTBOT_REDIS_PORT}"
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local
